### ISSUE TITLE
Dockerfile for Nginx 

### ISSUE THREAD

**Issue by majdal** [developmentseed/osm-seed#100]
Hello hello - After talking to @batpad about deployment possibilities, we thought that a production deployment using Docker is feasible. A useful component to make that work is to use Nginx as a load balancer/reverse proxy for the various services running. 

I don't have much experience with Docker, but I'll try to look into this more deeply over the next few days.

**Comment by batpad** [comment]
Hey @majdal - a simple `nginx` container to serve as a proxy would certainly help to make this setup possible to run on a single node using just `docker-compose` (without kubernetes).

You can see an example for a conceptually similar setup here: https://github.com/orma/openroads-vn-deploy

The important bits are:

  - The nginx conf to route traffic to different containers: https://github.com/orma/openroads-vn-deploy/blob/master/nginx/nginx.conf

 - Including `nginx` in the `docker-compose` file: https://github.com/orma/openroads-vn-deploy/blob/master/docker-compose.yaml#L55

There's a few additional things you may want, like th ability to setup SSL, etc. - fortunately, there's a lot of great articles on using similar setups to get a bit more understanding of how it all works, and how one would customize things - here's one article: https://dev.to/domysee/setting-up-a-reverse-proxy-with-nginx-and-docker-compose-29jg

Would be super happy to review / work through a PR if this seems like something you might be able to take on.

**Comment by batpad** [comment]
@majdal the `letsencrypt`/ HTTPs setup does seem like a few moving parts. There does seem to be a few articles and options on doing this  - here's one that seemed reasonable: https://gilyes.com/docker-nginx-letsencrypt/ . It seems to be doing a little bit of magic though, I'll try and do a bit more reading on other approaches as well.

**Comment by majdal** [comment]
Alright, after a few calls with @batpad, I think this is what we'll be doing: 

1. Update `docker-compose.yml` to serve the plain `http` version of the website. We'll get `letsencrypt/HTTPS` to work in a separate PR. 
2. Make the PR based on the iD editor branch (#99), since it's pretty much ready to be merged. 
3. The `nginx` server will expose only the `web` service at root `/`, and the `id` editor service at `/edit`, matching the `openstreetmap.org`. We won't expose the `db` service directly.

So, to do that, there are a few things that need to be done: 
1. Create a Dockerfile for nginx, using the nginx [official](https://github.com/docker-library/docs/tree/master/nginx) Docker image. 
2. Create an `nginx.conf` file configured with proxies to the `web` and `id` services. 
3. Add `nginx` as a service to `docker-compose.yml`

[Right now](https://github.com/developmentseed/osm-seed/blob/id-editor/openstreetmap-website/config/production.conf#L1), the application is served through an Apache server, on port 80. **Correct me if I'm wrong**, but what I should do is have Apache listen to a different port (say 8001), and expose that in `docker-compose`, then have `nginx` proxy port 80 to 8001 on the `web` service?

**Comment by majdal** [comment]
Oops... I accidentally closed the issue 😅

**Comment by batpad** [comment]
> Right now, the application is served through an Apache server, on port 80. Correct me if I'm wrong, but what I should do is have Apache listen to a different port (say 8001), and expose that in docker-compose, then have nginx proxy port 80 to 8001 on the web service?

@majdal right now, the website runs using apache, which runs on port 80 on the container. This line exposes and forwards that as port 80 on the host machine: https://github.com/developmentseed/osm-seed/blob/develop/docker-compose.yml#L9

Apache will continue serving on port 80 on the container, but it will no longer need to expose a port on the host machine. Port 80 will instead be exposed and forwarded by `nginx`.

Internally, all the containers within the `docker-compose` setup are on a private network, and `nginx` is able to ReverseProxy to the apache running inside the container without `apache` itself needing to be exposed to the outside World via the host.

So, `nginx` will now forward traffic to applications on different containers based on the `server_name`. Your `nginx` configuration will probably look something like this:

```

http {
    server {

        listen 80;
        server_name osm-web.local; # make configurable

        location / {

            proxy_pass         http://web:80; # docker-compose handles the networking so you can refer to a container by its name in the `docker-compose` file: https://github.com/developmentseed/osm-seed/blob/develop/docker-compose.yml#L3
            proxy_redirect     off;

            # It's a good idea to forward headers to the application
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;

        }
  }
}
```

^^ and then you can have different blocks that might forward to the `iD` container for example, based on a `server_name` or `location` inside the `nginx` configuration.

Does that make sense? So, apache can continue serving on port 80 inside the container. It just no longer needs to forward a port to the host - instead `nginx` will forward port 80 to the host, and handle sending requests to other containers via the `proxy_pass` directive.

**Comment by batpad** [comment]
We are definitely going to go down the route of handling the routing / DNS and SSL in the Helm / Kubernetes setup as per #216 - I don't think it makes sense to have a separate nginx container for the docker-compose setup at this point. Can re-open if it seems necessary.
