### ISSUE TITLE
Updating the OMS GIS database with diff files

### ISSUE THREAD

**Issue by Rub21** [developmentseed/osm-seed#103]
We have a container to generate osm-seed planet dump files, the planet files are generating every 5 hours, we don't have the functionality to generate diff files minutely nor hourly. The 5 hours could be customized to less time too, it is only a cron job. 

The issue is how we can update our GIS database whit out diff files? since we are not generating such files. On option could get two different planet files and get the diff from them, using [Osmconvert](https://wiki.openstreetmap.org/wiki/Osmconvert#Retrieving_the_Differences_between_two_OSM_Files) and then pass that file to imposm to update the DB,  I am still not sure if that could work. I would like to hear your ideas.

cc. @batpad @geohacker @kamicut @olafveerman

**Comment by geohacker** [comment]
> we don't have the functionality to generate diff files minutely nor hourly.

@Rub21 what is stopping us from creating diff files? we can run osm2pgsql between the containers to generate hourly diffs and apply them automatically?

**Comment by batpad** [comment]
@geohacker are you able to point to documentation / an example of generating minutely files?

**Comment by geohacker** [comment]
I think this would do:

1. osmosis for creating diffs https://wiki.openstreetmap.org/wiki/Osmosis/Replication#Server-side_Replication
2. and importing that using osmosis or osm2pgsql https://wiki.openstreetmap.org/wiki/HowTo_minutely_hstore#Import_Replication_Data_using_Osm2Pgsql

**Comment by batpad** [comment]
Thanks @geohacker - @Rub21 - can we try using the same `osmosis` container definition we have now, but setup with a different `CMD` to run the minutely replication?

And I guess we will be using `imposm` instead of `osm2pgsql` to get the diffs into the GIS db?

**Comment by Rub21** [comment]
As per our conversation with @batpad 
> can we try using the same osmosis container definition we have now, but setup with a different CMD to run the minutely replication?

We are going to create another container to create the replication file minutely or hourly. 

>  imposm instead of osm2pgsql to get the diffs into the GIS db?

We are using imposm, because it is much faster and what is recommended by Tegola team.

**Comment by geohacker** [comment]
@Rub21 I think we'll use https://imposm.org/docs/imposm3/latest/tutorial.html#updating ?

**Comment by Rub21** [comment]
This is done!!
