### ISSUE TITLE
Adding Tasking Manager 

### ISSUE THREAD

**Issue by majdal** [developmentseed/osm-seed#104]
Talking with @batpad, it seems like now is the time to include the HOT OSM [Tasking Manager](https://github.com/hotosm/tasking-manager) in this project. 

It seems simple enough, since the project is already [Docker-ized](https://github.com/hotosm/tasking-manager/blob/develop/Dockerfile).

**Comment by kamicut** [comment]
One thing that I'm wondering about is if we should have a fork of TM that is customized without the HOT-OSM splash. Right now there isn't a way to modularize this in TM. What would a TM for OSM-seed look like?

**Comment by majdal** [comment]
Well, osm-seed hasn't removed any of the osm-specific branding from the iD or the website, so I'm not sure if removing the HOT-OSM splash is within the scope of the project. Although I think it _would_ be better with a "generic" the splash page.

**Comment by Rub21** [comment]
Tasking manager was added to osm-seed https://github.com/developmentseed/osm-seed/tree/develop/images/tasking-manager-api
