### ISSUE TITLE
Namespace services

### ISSUE THREAD

**Issue by majdal** [developmentseed/osm-seed#105]
Hello all - I'm starting to deploy `osm-seed` for my own project, and I have my own app, which has a `web` component and a `db` component. Since the typical use scenario of `osm-seed` includes taking the `docker-compose.yml` file and customizing it for the specific setup of a project, I think it might make sense to namespace all of the services of `osm-seed` in `docker-compose`, allowing the user to define their own `web` and `db` services. e.g. `db` becomes `osmseed-db`, and so on. 

Does that make sense? Is there a better solution? Is this the right time to make such a change?

**Comment by geohacker** [comment]
With k8s all containers are appropriately namespaced. docker-compose will now be recommended only for testing and not for running in production so we may not get to this.
