### ISSUE TITLE
Use persistent disk on non-GCP deploys

### ISSUE THREAD

**Issue by batpad** [developmentseed/osm-seed#107]
Currently, we have persistent disk configuration to work with `GCE` persistent disks: https://github.com/developmentseed/osm-seed/blob/develop/helm/osm-seed/templates/db-pd.yaml#L17

We need to add an option in `values.yaml` which specifies the cloud provider - like `gcp`, `aws` (and in the future `none` / `self`) and accordingly configures persistent storage for the specified target.

I will do research on specifying persistent storage on AWS with EKS and then make the required changes to conditionally handle setting up of the persistent disk.

cc @Rub21 @olafveerman

**Comment by Rub21** [comment]
We added the `cloudProvider`  variable  it could be `minukube`, `aws` or `gcp` , https://github.com/developmentseed/osm-seed/blob/ed89ef72084b551635885ecb712361777834df02/helm/osm-seed/values.yaml#L10 ,
