### ISSUE TITLE
Use Dynamic Provisioning for Persistent Storage

### ISSUE THREAD

**Issue by batpad** [developmentseed/osm-seed#113]
Relates to #107 

Kubernetes offers two methods for attaching persistent storage to your cluster - "Static Provisioning" and "Dynamic Provisioning". In Static Provisioning, you need to create the persistent volume in your cloud system, and  then create a `PersistentVolumeClaim` to make it available to your pods that can then use the `PersistentVolume` from the claim.

This is fine and works, but includes the added overhead of having to manually create the persistent volumes and pass in their `name` / `VolumeID`. If we need more persistent volumes for different pods, this will start to get unwieldy.

Kubernetes also gives us the option to use "Dynamic Provisioning". Here, we define a `StorageClass` that will define how to provision new persistent volumes. We can define in the `StorageClass` whether we want to use `GCE` persistent volumes, `ELB` volumes on AWS, or something else. Then, when a `StatefulSet` resource requests for a persistent volume, it only needs to specify the size of volume it needs, and the cluster will automatically provision the new volume based on the backend specified in the `StorageClass` and make it available to the pod.

More documentation on defining Storage Classes: https://kubernetes.io/docs/concepts/storage/storage-classes/

I don't think there's an urgency to do this, just wanted to ticket as this would probably be the proper long-term solution to handle persistent storage.

cc @Rub21

**Comment by geohacker** [comment]
We do this already
