### ISSUE TITLE
Manage whether to deploy templates or not with `enabled` flag

### ISSUE THREAD

**Issue by batpad** [developmentseed/osm-seed#117]
Right now, we often want to deploy `osm-seed` and we want some resources "commented out" - for eg. deploy without `iD` or Replication enabled, etc.

Currently, we do this in a slightly janky way by temporarily removing those templates and deploying, etc.

We should ideally manage all of this with some options we specify in `values.yaml`.

So for eg. one should be able to specify `replication.enabled = false` or so, and then it should not apply any of the templates related to replication (using `if` statements in the template).

That way, it will be much easier to manage the entire state of the deployment only by specifying options in `values.yaml`.

cc @Rub21

**Comment by Rub21** [comment]
@batpad I added  this functionality in this PR: https://github.com/developmentseed/osm-seed/pull/121
