### ISSUE TITLE
Fix populate-apidb container to use latest version of osmosis

### ISSUE THREAD

**Issue by batpad** [developmentseed/osm-seed#119]
We seem to be using the incorrect binary of osmosis  here: https://github.com/developmentseed/osm-seed/blob/0aa56471dc786a73b96a767fa0096f699045e31a/populate-apidb/Dockerfile#L27

The newly built package will be found in `package/build/distribution/` as a `.tar.gz` - this is what we need to use as the files inside `package/bin/` are not actually updated with the `gradlew assemble` command.

@Rub21 I've created a PR with this change here: https://github.com/developmentseed/osm-seed/pull/118

**Comment by Rub21** [comment]
This is good @batpad , The PR  was already Merged !! Closing this ticket
