### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by aaj013** [developmentseed/osm-seed#137]
When I try to run 'docker-compose build', it throws some compilation error at 21% as in below screenshot
![osm-seed error](https://user-images.githubusercontent.com/5847582/49921999-56a5dd80-fed5-11e8-86c2-97e9207829fd.png)

**Comment by aaj013** [comment]
@geohacker Please have a look and guide if I'm doing anything wrong.

**Comment by Rub21** [comment]
@aaj013  could you run `docker-compose build --no-cache`? , I am trying to recreate this error in an Ubuntu machine. maybe it is because it did not install some packages in the previous step.

**Comment by Rub21** [comment]
@aaj013 , I found the error, it was because some update from  libosmium , protozero , I have fixed it, could you try again building the containers. 
 https://github.com/developmentseed/osm-seed/commit/f26320558d3dcc8f358d83293935d3d168f20b4d#diff-dd06b820ecd44c034b1260fa4be36e83

**Comment by aaj013** [comment]
Hey @Rub21, thanks a lot! It's working now.
