### ISSUE TITLE
Cant install osm-seed to k8 cluster

### ISSUE THREAD

**Issue by Pflegusch** [developmentseed/osm-seed#144]
Whenever I try to follow along the Readme in the helm subfolder and execute the command `helm install -f myvalues.yaml osm-seed/`, it says `Error: failed to download "osm-seed/" (hint: running `helm repo update` may help)`. Running `helm repo update` doesnt help either. 

If I change to the directory above and run `helm install -f osm-seed/myvalues.yaml osm-seed/`, it throws me the following error: `Error: release wishful-squirrel failed: PersistentVolume "wishful-squirrel-pv" is invalid: [spec.accessModes: Required value, spec.capacity: Required value, spec.capacity: Unsupported value: core.ResourceList(nil): supported values: "storage", spec: Required value: must specify a volume type]`.

Can anyone help?

**Comment by batpad** [comment]
Hi @Pflegusch -

Could you paste the contents of your `myvalues.yaml` with the values you are over-riding the defaults with? Also, what k8s backend are you installing onto? Is this a local minikube instance or a cloud provided k8s cluster?

**Comment by Pflegusch** [comment]
Hi @batpad, myvalues.yaml can be found here (https://pastebin.com/raks1tnW). 

Its a cloud provided k8 cluster, I didnt try to do it with minikube yet.

**Comment by batpad** [comment]
@Pflegusch I see as the `cloudProvider` value you have specified `hns`. Unfortunately, at this point, we only support values of `aws`, `gcp` or `minikube`. I'd be curious what `hns` refers to? It's possible that we'd be able to work through the templates to add this as a valid cloud provider, but I expect that this will not work as things are currently setup.

We have a few places in the templates where we make decisions based on the cloud provider name, eg: https://github.com/developmentseed/osm-seed/blob/develop/helm/osm-seed/templates/db-pd.yaml#L15 . Ideally, this would be improved to have more granular options, but we felt it easier for the user to just specify the cloud provider name and then take care of some of the details like differences in volume types within the helm chart. Unfortunately, that means that we can currently only support backend providers we have explicitly added support for.

If you give more details about the cloud provider, I'd be happy to work with you to outline a ticket to figure out what it would take to add support - it's very likely small tweaks that would make it work.

However, I'd also recommend setting up via `minikube` to start, to just check that things come up and work.

**Comment by Pflegusch** [comment]
Hey @batpad, 

sorry for the confusion, the cloudProvider should actually be openstack. I will try minikube now. :)

**Comment by batpad** [comment]
> sorry for the confusion, the cloudProvider should actually be openstack.

I would be very interested in getting this working on `openstack`. I'm not sure we'd have the time to do all the work required, but if you were happy to work through some of the issues, I'd be happy to try and help / outline a ticket with what would be required, etc. It's also entirely possible that just entering `gcp` as the cloud provider for now will mostly "just work" - my hunch is there might be minor changes to the persistent volume configuration, and maybe a different setup for the LoadBalancer setup, but ideally it should be quite simple to add a new provider.

Some of this code hasn't been touched in some time, and I wouldn't be surprised if a couple pieces are a bit broken, but hopefully between me and my colleague @Rub21 we should be able to resolve any obvious issues with the current setup. Feel free to make tickets and we'll get back to you as soon as we can.

In general, I'd be curious as to your use-case, also maybe to help you figure out if `osm-seed` is indeed a good fit - feel free to email me at sanjay (the at symbol) developmentseed.org .
