### ISSUE TITLE
Moving osm-seed to an organization

### ISSUE THREAD

**Issue by geohacker** [developmentseed/osm-seed#155]
We have more and more projects using osm-seed. This means that the website container code for instance could have changes that doesn't make sense for other projects. 
The best way to manage multiple forks of osm-seed is:
* Keep this parent repository for our usecases
* Start a new osm-seed organization
* Move each Dockerfile into its own repository. So openstreetmap-website gets a repo and tiler gets a repo. We can keep a master repo that ties it all together. 
* This way, projects can fork only necessary repos and make changes without having fork the entire project and lose out on updates.

@batpad @Rub21 @kamicut  if you think this is a good idea, I can create the repo.

**Comment by geohacker** [comment]
Created an organization https://github.com/osm-seed

**Comment by batpad** [comment]
@geohacker - with the new setup and the public helm chart in the [osm-seed-chart](https://github.com/developmentseed/osm-seed-chart/tree/gh-pages) repo, do you think we still want to do this?

**Comment by geohacker** [comment]
Yeah this is no longer required. I will remove the org.
