### ISSUE TITLE
Upgrade to helm v3

### ISSUE THREAD

**Issue by batpad** [developmentseed/osm-seed#158]
We should upgrade to Helm v3. It should be backwards compatible and not involve anything other than changing the version of helm we use.

If we do this soon, we won't need to worry about migrating existing instances from using helm v2 to v3 as we can just redeploy all instances.

**Comment by syncush** [comment]
Hey!
Are you planning to upgrade anytime soon?

If you need an extra pair of working hands, I am willing to help.

**Comment by batpad** [comment]
Sorry for not responding earlier!

We've tested the charts now with helm v3 and are using helm v3 with the existing charts to deploy, so turns out there was nothing needed for the upgrade in the end other than just using the v3 binary for new installs.

Closing here.

**Comment by batpad** [comment]
(Please feel free to tag / re-open if there seem to be any issues specifically with helm v3, but as far as we've been able to tell, things just worked with using the helm v3 binary, as long as the cluster has not been initialized with `tiller` etc using helm v2 - if your cluster has already been initialized with helm v2, there maybe additional steps required to migrate to v3).
