### ISSUE TITLE
Use Chartpress to handle image builds and Helm Chart management

### ISSUE THREAD

**Issue by batpad** [developmentseed/osm-seed#164]
[Chartpress](https://github.com/jupyterhub/chartpress) was written as a stand-alone module as part of the JupyterHub project to help with a lot of the same problems we are currently facing on `osm-seed`.

They have a folder containing "images", which, similar to osm-seed, contains a folder each with its respective `Dockerfile`. When pushes are made to the repository, they want to be able to update the docker images, but run into the same problems of not wanting to rebuild images if unnecessary, but also be able to reference the correct image tags in the values.yaml and Helm charts without manually maintaining a list of different images at different tags.

Chartpress handles all of this, requiring a simple definition in a chartpress.yml file, where we define configuration: https://github.com/jupyterhub/chartpress#configuration

Chartpress will also optionally handle publishing a Helm Chart to gh-pages of a Github repository, which will give us a cleaner route to customizing specific containers and configurations in osm-seed by including and over-riding elements of the Helm Chart, rather than forking the repository.

The first step here would be to get a Chartpress configuration for osm-seed and making sure we can run the `chartpress` command locally and have all the images build, and populate the values file successfully:

 - Create chartpress.yml file for repo. We **may** want to reorganize our folder structure to put all the folders with Dockerfiles into an `images/` folder. This is the expected layout for Chartpress and while not required, seems like a cleaner structure in general, and I would advocate for borrowing as many patterns from JupyterHub as we can as the overall structure of what they are doing is very similar and they have obviously had more time to spend on this architecture than we have.

 - In the Helm Charts, create different `version` variables for each docker container, instead of using a common top-level git-sha as version. We then plug the path to those values in our Chartpress config and Chartpress should handle correctly setting the image tag / version for each of the containers.

 - Modify the CircleCI config to run `chartpress` to build and push images (which it will then do only if something in that folder has changed).

After this, we can ticket out separately publishing of the Helm Charts and making them re-usable / configurable to avoid the forking problem.

This is the repository I will use as example / guidance to restructure our repository a little and create the Chartpress configuration: https://github.com/jupyterhub/zero-to-jupyterhub-k8s .

cc @geohacker @Rub21

**Comment by geohacker** [comment]
This sounds really good to me @batpad.

**Comment by batpad** [comment]
This is merged! I will create a separate issue to improve documentation and examples, but this is basically working, using chartpress to build images and publish to dockerhub, and publish a public Helm chart that can be used to deploy.
