### ISSUE TITLE
Offline use in production

### ISSUE THREAD

**Issue by alfredott** [developmentseed/osm-seed#169]
Hello,

At first, thank you for you work in the osm community.

I'm interested in using your project in production in my company.
Here are some details about our use case :
- We only want to use the tile generation part of osm-seed (no editor or minute diff)
- We want to use your projection in production, with hundreds of clients
- We are using an offline network (no access to internet)
- We would like to update data regularly (every 2-3 months or so)

Do you think that osm-seed would be adapted to our use case, and to the several details that I enumerated ? Do you know other companies that use osm-seed offline ?

I personally think that a helm chart really is the right way to go to serve osm tiles. That's why I'm asking :)

Thanks again for your work, and thanks in advance for your answer, have a good day !

**Comment by batpad** [comment]
Hi @alfredott - thank you for the ticket and your interest.

I don't really see why what you describe cannot be done by setting up osm-seed or an osm-seed like instance within your internal / offline network. We have not yet had to do this, so there's a chance there might be minor issues like some dependencies coming from a CDN or something, but those would be easy to fix - I don't see any fundamental problems with this. If you do land up trying to run it offline and run into issues, we'd definitely be interested in Pull Requests to support an offline use-case.

We've used osm-seed at varying scales, and scaling is really a matter of having enough hardware, and perhaps some fine-tuning of container node allocations, etc.

For data updates, etc. - is this some custom data or do you mean data for all of planet OSM? If it is all of planet, this is definitely doable, but the initial data import can take a long time, and you will need some planning for data updates. If it's a smaller custom data-set, this should not be much of a concern as long as you're able to use standard OSM tools to import / update data, etc.

> I personally think that a helm chart really is the right way to go to serve osm tiles. That's why I'm asking :)

Honestly, this is the same simple thought that's led to this project - Helm + Kubernetes just seemed like a robust, convenient way to organize an OSM deployment with all the variety of tools, etc. one might want along-with it. The goal is definitely to make it as easy as possible to pick and choose just the parts you need. We are currently working on [this ticket](https://github.com/developmentseed/osm-seed/issues/164) in [this PR](https://github.com/developmentseed/osm-seed/pull/166) which should follow more common `helm` practices and publish a Helm Chart that should make it much easier to then create a customized version of osm-seed without forking the project.

Especially if you have some experience with Helm, would be great to hear your thoughts - we hope to have the re-organization to use Chartpress done soon, hopefully within the next couple weeks. I think it will then be a bit cleaner to over-ride and customize things without needing to fork. But you should already be able to test things out.

We do have a few pieces moving currently in terms of branches and works-in-progress, so you might see the project structure change a bit drastically as per the above PR in the next weeks.

**Comment by alfredott** [comment]
Hello !

Thanks a lot for your quick answer, and the insights about the future of the project !

To be clear, I really do not need the editor and minute diff features of osm-seed. I rather want to update my data every 2-3 months or so.

Am I right to say that I could just "turn off" the following parts of the project :
- id-Editor
- osm-web + api
- apidb
- replication-job
- planet-dump
- db-backup-restore
- s3 (the one related to .pbf files)
- osm-processor
- populate-apidb
... and only use :
- tiler-imposm
- tiler-db
- tiler-server
- tiler-visor

I'm still not an expert in helm, thus I'm not sure "turning off" modules is possible. In the way I see it, it could be configurable.
For example :
- If you run your chart **without** the "tilerOnly" option, it runs the way it is right now.
- If you run your chart **with** the "tilerOnly" option, it only runs the 4 parts I mentionned earlied.

And then, every 2 months, I would just give tiler-imposm an updated pbf file I would get from the internet.

I know it removes a big part of osm-seed, but I really think helm is the way to go.
Do you think it still makes sense to use osm-seed ?
Would it be possible to change the pbf file tiler-imposm every 2 months, still making sure that the users still have tiles during the update ?

Thanks in advance for your answers, bye !

**Comment by a-hahn** [comment]
@alfredott This project https://github.com/Overv/openstreetmap-tile-server is a pretty much simplified approach for hosting a tile server using docker. It works really well but it doesn't offer the same scaling possibilities as a kubernetes solution.

**Comment by batpad** [comment]
@alfredott while the new project structure we are working on over at https://github.com/developmentseed/osm-seed/pull/166 will publish a public Helm chart and make it much easier to customize without forking this repository, in your case I'm inclined to agree with @a-hahn - if you only wish to run the tile server without any of the other associated OSM tools, there's likely simpler ways to do this.

With regards to being able to do a fresh update of the tiler-db from a pbf without causing down-time, that's a good question :-) - I'd imagine there would be some way to setup a separate tiler-db instance, load the data, and only then switch the tiler-server over. We've not needed to do this yet, though.

**Comment by batpad** [comment]
@alfredott I'm going to go ahead and close this issue as there's nothing actionable.

If you want to create a separate issue to make running only the tile-server and db easier / more configurable, would be happy to look at it / drop links to documentation once we get this Helm chart publishing stuff working.

Of course, feel free to re-open if you run things offline and face any specific issues.

**Comment by alfredott** [comment]
Hello :)  
I've just realized that I forgot to answer your messages.
I've actually already worked with https://github.com/Overv/openstreetmap-tile-server (I had made an issue on this project), but I found that it was a bit cleaner to work with a helm chart, and that is why I decided to create this issue on osm-seed :)
I will continue trying to work with osm-seed (it's not my main project right now), and I will contact you if I need some help.

Thanks a lot !
