### ISSUE TITLE
tiler-imposm fail when importing natural earth

### ISSUE THREAD

**Issue by bro52** [developmentseed/osm-seed#171]
step to reproduce: 
->  run osm-seed/tiler-imposm/scripts/natural_earth.sh
get the error : 
_Archive:  0.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of 0 or
        0.zip, and cannot find 0.ZIP, period._

To correct the issue : 
change all the url in  "dataurls=( "http://naciscdn.org......" from http to http**s**.
because when you curl the http address you got : 
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://naciscdn.org/naturalearth/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip">here</a>.</p>
</body></html>

**Comment by geohacker** [comment]
Hi @bro52, thanks for reporting! Yes we ran into this as well and this is fixed in the [`osm-seed`](https://github.com/developmentseed/osm-seed/pull/160) branch. This will likely land in master in a few weeks. We're working on some refactors on how the images are organized and built.
