### ISSUE TITLE
Improve HTML page and docs for Helm chart

### ISSUE THREAD

**Issue by batpad** [developmentseed/osm-seed#173]
We now have a public Helm chart that gets published to https://github.com/developmentseed/osm-seed-chart/tree/gh-pages with the "frontend" at https://devseed.com/osm-seed-chart/ .

We should display a proper list of all versions available, some links to documentation, etc., something like this: https://jupyterhub.github.io/helm-chart/

We can likely use the same pattern as https://github.com/jupyterhub/helm-chart

**Comment by Rub21** [comment]
@batpad , I set the site for osm-seed heml charts : https://devseed.com/osm-seed-chart/

**Comment by batpad** [comment]
@Rub21 this looks fantastic! Thank you so much!
