### ISSUE TITLE
[tiler-server] Tegola project version

### ISSUE THREAD

**Issue by bro52** [developmentseed/osm-seed#179]
Hey  guys,

Thanks for the great work and the latest update of the devel branch. 

I have a question about the tiler-server : 

In the Dockerfile the version of the tegola project  is  v0.8.1 
`
ENV VERSION="v0.8.1"
RUN cd /go/src/github.com/go-spatial/tegola && git checkout v0.8.1
`
The last release of the Tegola project is v0.12.1. Is there any reasons  (breaking changes ? ) not to update to the newest version ? 

Thx a lot,

Regards

**Comment by geohacker** [comment]
Hi @bro52, I think upgrading to v0.12.1 should be alright. I couldn't see any changes that are listed in breaking changes that would affect us. If I remember right, I did try 0.11 a little while ago and it was fine.

We'd be glad if you can send us a PR upgrading tegola to 0.12.1. Thank you!

**Comment by bro52** [comment]
Hey,
Thanks for the quick reply. 
I have tried  with Tegola v0.12.1. 
Everything seems ok, no bugs nor stranges logs. I'm gonna do a  PR at the end of the week after some tests.

Cheers,

**Comment by geohacker** [comment]
Thank you @bro52! I'll leave this ticket open until we upgrade Tegola. 

cc @batpad
