### ISSUE TITLE
Nominatim

### ISSUE THREAD

**Issue by geohacker** [developmentseed/osm-seed#180]
We should add Nominatim to osm-seed. The nominatim setup should pull minutely updates from the location where osm-seed replication is storing replication. 

As OpenHistoricalMap is using osm-seed, it is critical for us to add Nominatim at the moment to address some key issues https://github.com/OpenHistoricalMap/issues/issues/192 and https://github.com/OpenHistoricalMap/issues/issues/196

@Rub21 do you think you can take a stab at this? We already have a Dockerfile https://github.com/OpenHistoricalMap/ohm-nominatim/tree/master/docker and related setup details in the ohm-nominatim repository. We should write k8s templates, add to chartpress and deploy with Helm.

cc @batpad

**Comment by Rub21** [comment]
Nominatim was added in  osm-seed : https://github.com/developmentseed/osm-seed/tree/develop/images/nominatim
