### ISSUE TITLE
Test osm-seed on non-AWS or GCP providers, clarify documentation

### ISSUE THREAD

**Issue by batpad** [developmentseed/osm-seed#208]
Currently, we have a few places where we hard-code the cloud provider as AWS or GCP, and configuring the values for other providers can be a bit confusing.

Let's:

 - Test that we can install osm-seed on a non-AWS or GCP environment. I'd recommend testing on a Digital Ocean kubernetes cluster.
 - Check if anything fails, and fix the values appropriately.
 - Clean up the values file and documentation to make clear how to run on any Kubernetes cluster.

The hard one to fix here would be the uploads to s3 and GCP storage. Speaking to @geohacker, let us just not upload to storage on non-AWS or GCP environments. The code should already save to a local disk - we can just make sure we mount persistent storage as the disk things like minutely replication files get saved to. We can figure out serving those files separately if they need to be web accessible.

This would be nice to do as there have been a few requests recently to run in non-AWS or GCP environments, and there is no reason it shouldn't - it just seems like we may have small things that need fixing since we have never tested this.

cc @geohacker @Rub21

**Comment by geohacker** [comment]
We are now successfully running on Azure https://github.com/hotosm/tf-azure-osm-seed/
