### ISSUE TITLE
nominatim Required value: must specify a volume type]

### ISSUE THREAD

**Issue by marshall20** [developmentseed/osm-seed#213]
When installing the last public chart on minikube without specific values file I get this error

PersistentVolume "test-1.0-nominatim-pv" is invalid: [spec.accessModes: Required value, spec.capacity: Required value, spec.capacity: Unsupported value: core.ResourceList(nil): supported values: "storage", spec: Required value: must specify a volume type]

**Comment by batpad** [comment]
@marshall20 thanks for the report!

@Rub21 let me know if you're able to look? Possibly we can solve this with default values for these things?

@marshall20 - I can see that we have likely not tested a vanilla install on `minikube` for some time - I'll try and find sometime this week to attempt this and try and fix errors - I suspect there might be a few more things broken on vanilla `minikube` - this is definitely something we'd want to fix as this should ideally work, so thanks again for reporting and hope we're able to work through this soon.

**Comment by Rub21** [comment]
@batpad @marshall20 , I've just added support for minikube Persistent disk : https://github.com/developmentseed/osm-seed/pull/214 ,  hope this fix you issue,  happy to help if there are other issue.
