### ISSUE TITLE
Improve web email setup through documentation and configuration

### ISSUE THREAD

**Issue by dakotabenjamin** [developmentseed/osm-seed#222]
Currently (on docker-compose) I have had to make a few manual changes to get the email to work. The envvars in envs/.env.web contain vars for the mailer, but those do not get applied to the web container settings. In images/web/start.sh I added a few lines of `sed` commands to replace the $workdir/config/settings.yml lines for smtp and email configs. I have also run into issues with using Amazon SES and Sendgrid which we are currently debugging. 

Since email is required for creating user accounts using the web interface, I propose that these configurations be in place by default using the envvars provided. I also think that the documentation should be added for the email configuration and to explain other external factors (for example, EC2/Azure VMs blocking port 25 by default).

**Comment by mvexel** [comment]
I'm having some trouble with setting up email parameters correctly as well. If I use the following settings in the 'official' rails port docker setup, I do receive the confirmation emails:
```
smtp_address: "smtp.mailgun.org"
smtp_port: 587
smtp_domain: "mysubdomain.mailgun.org"
smtp_enable_starttls_auto: false
smtp_authentication: "plain"
smtp_user_name: "postmaster@mysubdomain.mailgun.org"
smtp_password: "mypassword"
```
However, if i set up my `.env.web` as
```
# Mailer settings 
MAILER_ADDRESS=smtp.mailgun.org
MAILER_DOMAIN=mysubdomain.mailgun.org
MAILER_USERNAME=postmaster@mysubdomain.mailgun.org
MAILER_PASSWORD='mypassword'
MAILER_FROM=no-reply@mydomain.com
```
and set
```
  :authentication => 'plain',
  :enable_starttls_auto => false
```
in `images/web/config/action_mailer.rb`, I don't get any confirmation emails.
I am not rails-savvy enough to see if the emails somehow get stuck in the Action Job scheduler, or if they just never make it onto the job queue, but they don't seem to arrive at mailgun.

I do see
```
I, [2022-01-24T21:33:17.669897 #317]  INFO -- : [4ce66a0c-c3f8-4733-9a9b-73f03f36b903] [ActiveJob] Enqueued ActionMailer::MailDeliveryJob (Job ID: 4abe3e23-0d0b-4c5f-aca0-feaf22ae31aa) to DelayedJob(mailers) with arguments: "Notifier", "signup_confirm", "deliver_now", {:args=>[#<GlobalID:0x0000556b862a87e8 @uri=#<URI::GID gid://open-street-map/User/1>>, #<GlobalID:0x0000556b862aff20 @uri=#<URI::GID gid://open-street-map/UserToken/11>>]}
``` 
suggesting that the email was at least queued.
Happy to help improve documentation.

**Comment by geohacker** [comment]
We have revised documentation to setup emails better here https://github.com/developmentseed/osm-seed/tree/develop/images/web#email-configuration. I hope this addresses all the questions so far. Please feel free to reopen if something doesn't look right!
