### ISSUE TITLE
web image: old version of cargo can't read Manifest

### ISSUE THREAD

**Issue by mvexel** [developmentseed/osm-seed#223]
The apt-provided version of cargo is too old to read the Manifest file: `this version of Cargo is older than the 2021 edition`
Relevant lines of the Dockerfile https://github.com/developmentseed/osm-seed/blob/develop/images/web/Dockerfile#L125-L127

I made the following changes to make it work for me.

```
--- a/images/web/Dockerfile
+++ b/images/web/Dockerfile
@@ -122,9 +122,9 @@ RUN apt-get install -y libv8-dev
 RUN echo "gem 'terser', '~> 1.1.3'" >> Gemfile
 # RUN gem install nokogiri -- --use-system-libraries
 
-RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
+RUN apt-get install -y cargo
 RUN git clone https://github.com/shssoichiro/oxipng.git
-RUN cd oxipng && $HOME/.cargo/bin/cargo build --release && cp target/release/oxipng /usr/local/bin
+RUN cd oxipng && cargo build --release && cp target/release/oxipng /usr/local/bin
 
 # Install app dependencies
 RUN bundle update mimemagic
```

**Comment by batpad** [comment]
Thanks @mvexel !

@Rub21 I know you made some changes related to this `oxipng` stuff to fix something recently, would you have time to look? I can also try and find some time tomorrow.

**Comment by Rub21** [comment]
@mvexel @batpad , this is been fixed in the PR https://github.com/developmentseed/osm-seed/pull/220,  closing the ticket!
