### ISSUE TITLE
Add better tags to published Charts

### ISSUE THREAD

**Issue by batpad** [developmentseed/osm-seed#236]
Published charts should include whether they came from `develop` or a branch so it's easier to find - there should be some chartpressy way to do this. Filing this as stub.

cc @Rub21

**Comment by batpad** [comment]
@yuvipanda - do you have any recommendations here?

Right now, this is where our chart is published: https://devseed.com/osm-seed-chart/ - every time we push from any branch, it will create a new version entry in that list. This, of course, gets very painful.

My ideal situation would be:

All pushes from the `main` branch get tagged as `Stable` releases.

All pushes from the `develop` branch get tagged as `Development` releases.

All other pushes get tags as `Test` or so releases.

Just checking if there might be anything on the top of your head where this pattern is implemented - it seems like it shouldn't be too hard to do anyway.

**Comment by yuvipanda** [comment]
https://jupyterhub.github.io/helm-chart/ has separate links for stable and dev releases, and seems similar to what you want. Most of the logic I think is in https://github.com/jupyterhub/helm-chart/blob/gh-pages/index.md and https://github.com/jupyterhub/helm-chart/blob/gh-pages/info.json - magic courtesy of the amazing @consideratio :)

It would be great to extract this from the jupyterhub/helm-chart repo and make it into a github template repo

**Comment by batpad** [comment]
This is done: https://devseed.com/osm-seed-chart/ - nice work @Rub21 

@yuvipanda thanks much! Let's look at this together when we are on the same continent again soon? I think a template repo for the chart sounds like a great idea - we've been super grateful and happy with the `chartpress` -> published Helm chart workflow and would be great to see how we can make this workflow even smoother, and perhaps easier to port to different contexts.

**Comment by yuvipanda** [comment]
@batpad yay, that looks pretty sweet. Nice work indeed, @Rub21 :)

And yes, let's chat when we meet next!
