### ISSUE TITLE
Error trying to set up the iD Editor on kubernetes

### ISSUE THREAD

**Issue by lquinonesp** [developmentseed/osm-seed#265]
I have been trying to conigure the iD editor following this [guide](https://github.com/openstreetmap/openstreetmap-website/blob/master/CONFIGURE.md#oauth-consumer-keys) from the OSM repository.

 I tried 

1. Creating oauth1 with Main Application URL: domain/id
2. And oauth2 application for my iD editor with RedirectURIs:
- domain/id
- domain/edit

I have updated the OAUTH_CLIENT_ID and OAUTH_KEY variables for both oauth1 and oauth2 applications and ran helm upgrade for the changes to take effect.

When I go to domain/id or domain/edit I get the following Application Error:

![image](https://user-images.githubusercontent.com/73253185/189219295-249258a1-0193-4994-b9ee-0e9b8a045b0d.png)

In the Ruby log I get the following message:
![image](https://user-images.githubusercontent.com/73253185/189220459-ef323c35-9261-478e-a691-745bf9f14a7e.png)

Is the integrated iD editor not part of this helm chart?

**Comment by batpad** [comment]
@lquinonesp thank you for the issue - the iD editor is always a bit janky to setup and we are hoping to improve the process - also, OSM recently changed how it defines environment variables - perhaps we missed updating our documentation somewhere? 

Super curious if you managed to get this fixed and if you're able to quickly share how so we can hopefully improve our docs. Thanks!

**Comment by lquinonesp** [comment]
@batpad I was able to fix this issue. At some point I did notice that I had my key and secret swapped through the confusion of OAuth1 having `Consumer Key`  and `Consumer Secret` while OAuth2 has `Client ID` and `Client Secret`, in the chart these are `OAUTH_CLIENT_ID` and `OAUTH_KEY`, respectively. However, the official OSM [CONFIGURE.md](https://github.com/openstreetmap/openstreetmap-website/blob/master/CONFIGURE.md#oauth-consumer-keys) specifies to create a OAuth2 but with this chart I could only get it working with OAuth1.  I would need to try again with OAuth2 to confirm if it can be done with the latest chart version.

**Comment by batpad** [comment]
@lquinonesp thanks for following up!

Haa, there was definitely something weird with the Oauth1 and Oauth2 - do let us know if you figure it out. This is a really easy mistake to make and I think it would be nice if osm-seed can handle creating a user in the db + setting up the OAuth keys automatically without this manual configuration - I *think* we had an issue for this, would definitely be good to look at again.

Thanks again for following up - feel free to reach out if you run into other issues - also always curious to know how people are using it.
