### ISSUE TITLE
Create a Dashboard to manage the website 

### ISSUE THREAD

**Issue by A0x01** [developmentseed/osm-seed#272]
Hi ,
Thank you for your great work on this amazing project . I would suggest to make a dashboard to manage the websites and have this feature :
- Manage Users [add , remove , edit ]  because it is hard to do it using the cli  for a non-technical admin 
- Create Api keys for other users to use it on apps

Thank You

**Comment by batpad** [comment]
@A0x01 yes! Thank you for the issue. It does seem like the process of creating users / keys and having to plug them all in is likely the biggest stumbling block when getting started with osm-seed.

There are some ideas already in this ticket: https://github.com/developmentseed/osm-seed/issues/259

Thanks for this issue - hopefully this is something we are able to prioritize soon (of course, if you have a good idea for this, PRs most welcome!).

**Comment by batpad** [comment]
Just cleaning up, am going to close this issue in favour of #259 .

To note, @Rub21 has done some fantastic work toward this already: https://github.com/developmentseed/osm-seed/pull/274 - @Rub21 whenever you have some time, might be nice to revisit that PR and see what we need to do to get it over the line - having a django app connected to the db where we can do things like this is really exciting and I think potentially allows us to do more interesting things down the line other than the user management things that are already possible in your PR.
