### ISSUE TITLE
Overview over components

### ISSUE THREAD

**Issue by srudin** [developmentseed/osm-seed#285]
I can see an overview over all components here: https://github.com/developmentseed/osm-seed#whats-included-now

However the descriptions are a bit short - also the component specific descriptions are focusing more on the technical aspects (installation etc.) than on explaining what the component is really for. I may have missed that but is there some kind of overview or explanations what these components are really required for and what dependencies exists?

We are planning to use osm-seed to host map data from geofabrik.de for a limited area. We are spending time on this because we have the requirement to be independent from public systems. So we don't need a lot - import and prepare the geofabrik data somehow, then make it available in the intranet. Do I need the planet-dump component for this? Do I need the tiler components? What about the different apis? That's what I need to find out and I feel the ReadMe alone isn't too much help...

**Comment by batpad** [comment]
> However the descriptions are a bit short 

Yea, that probably does assume some familiarity with the eco-system of OSM software.

The `web` and `db` containers are the only containers that are needed to import data and serve the data via the OSM API. But if you want the data to be available to users, you probably want map tiles - the `tiler` components generate vector tiles from the OSM data. The other tools are `nominatim` for geocoding requests, `Overpass` which is a general search tool, and you can probably look up more of each one on their project pages - but none of those are dependencies.

Whilst saying this - `osm-seed` is really ideal for when you need to edit and manage your own data using OSM software and tools. If your use-case is just importing data from OSM and serving it over an internal network, `osm-seed` **should** work, but perhaps something like Headway Maps fits the use-case a bit better: https://github.com/headwaymaps/headway

**Comment by srudin** [comment]
@batpad Ok interesting, thanks for the hint. Is the osm-seed team in any way related to this headway project?

We actually have an installation for our use case already and it is based on a number of custom built docker containers using some osm open source code (I'm saying "some" because this has been done years ago and the people involved have left already so we don't really know the source). We do know that it uses data from geofabrik.de and I think it is requested this stays this way - can headway import data from there?

We now need to migrate to k8 and when we saw the osm-seed helm chart we figured that would be the way to go and we'd just replace the entire existing solution. But I just saw headway has a helm chart as well... :-|

**Comment by batpad** [comment]
> @batpad Ok interesting, thanks for the hint. Is the osm-seed team in any way related to this headway project?

Nope - we've had some good interactions with the maintainer and I think it's a good project - very similar to osm-seed in some sense, but also fulfiling a very different use-case. For osm-seed, our primary use-case is really projects like openhistoricalmap.org who want to use the OSM software, but to map "other things" / things not in OSM. With Headway, the use-case seems much more similar to what you describe: you just want an extract of OSM and run all the normal OSM services, maps, geocoding, routing, etc. on your own infrastructure.

> We do know that it uses data from geofabrik.de and I think it is requested this stays this way - can headway import data from there?

Geofabrik data is in a standard OSM data format and I'm relatively certain that Headway would have a good way to import data from there. Geofabrik is the standard resource people use to get extracts of OSM data, so Headway will definitely have a way to import.

> . But I just saw headway has a helm chart as well... :-|

It seemed like a really good setup to me - have not had the time to try it out, so am unfamiliar with the details, but it definitely seemed like what I would use if my use-case was to use OSM data as-is, and not use it as a spatial data editing / user management platform, which causes a bunch of the complexity on osm-seed that you're running into.

**Comment by borys-spiridonov-yal** [comment]
@batpad I have a very similar use case and have already spent some time deploying osm-seed helm chart. 
Why do you recommend Headway instead of osm-seed? could you briefly list the main differences between those projects?
Thank you!

**Comment by srudin** [comment]
Thanks for the honest feedback - I came up with a different solution, details see https://github.com/developmentseed/osm-seed/issues/281
