### ISSUE TITLE
Please remove OSMOSIS

### ISSUE THREAD

**Issue by icemagno** [developmentseed/osm-seed#289]
I'm having a lot of problems when try to create database using standalone method.

First this: 
https://github.com/developmentseed/osm-seed/tree/develop/images/db

And then this:
https://github.com/developmentseed/osm-seed/tree/develop/images/populate-apidb

OSMOSIS is a realy pain.

Its complaining about a "users" table I don't have any idea what it talking about.

**Comment by Rub21** [comment]
hey @icemagno ,  could you try importing one of the geofabrick files: http://download.geofabrik.de/ ? , those files do not contain user value and some others,    if you are trying to import some other custom osm file into the DB, you need to remove the user and other, take reference the geofabrick files. e.g 👇 

<img width="845" alt="image" src="https://user-images.githubusercontent.com/1152236/227319721-4ff8fce7-1f79-4a46-88fb-2c64c2bf4f76.png">

To build a you custom file also , you need to use osmosis.

**Comment by icemagno** [comment]
Hi.
I found the problem. The database structure was not created.

I have to take a SQL to create it first. After that all goes fine.

I always use Geofabrik. Its the best of all.
