### ISSUE TITLE
Is the setup using a single database?

### ISSUE THREAD

**Issue by borys-spiridonov-yal** [developmentseed/osm-seed#294]
Both nominatim and overpass containers have the parameter for downloading the map:

```
PBF_URL: http://download.geofabrik.de/europe/monaco-latest.osm.pbf
OVERPASS_PLANET_URL: http://download.geofabrik.de/europe/monaco-latest.osm.bz2
```

It implies that the components have individual databases, is it correct? Can those components work with a single database instead?

**Comment by mmd-osm** [comment]
Nominatim runs on PostgreSQL, Overpass on a custom binary format. So the answer is no.
