### ISSUE TITLE
Add FTP  server  to serve for minute/planet  replication files

### ISSUE THREAD

**Issue by Rub21** [developmentseed/osm-seed#312]
Currently, most of our approach involves using AWS to store the minute replication files. In order to test the minute replication locally, we need to serve the files on an FTP server for consumption by other services.

cc. @batpad

**Comment by batpad** [comment]
@Rub21 I'm not sure why we need an "FTP" server - why can't we just put the replication files in a folder and serve them over http? Like planet.openstreetmap.org or so - not sure why it needs "FTP" here. FTP introduces security issues and general pain, not sure why we can't just copy to a folder on the machine that is then served over regular apache / nginx ?

**Comment by Rub21** [comment]
Yes, you are right. It needs to be only some nginx or lighttpd to serve those static files. Looks like FTP server sounds more broadly.

**Comment by Rub21** [comment]
done!
