### ISSUE TITLE
Convert secrets to Kubernetes Secrets

### ISSUE THREAD

**Issue by batpad** [developmentseed/osm-seed#64]
We should use `Secrets` to hold all sensitive configuration like passwords, etc. See https://kubernetes.io/docs/concepts/configuration/secret/ . So we'd create YAML files for secrets, that can get the secrets from `Values.yaml`, and then "mount" the secrets into the pods that need them.

This has two advantages:

 - when something is marked as a Secret, Kubernetes handles storing it more securely internally
 - We can put all the secrets in a single Secret volume and mount the same volume wherever we need access to those secrets, instead of defining the same parameters for every pod / deployment.

cc @Rub21

**Comment by geohacker** [comment]
Not relevant anymore
