### ISSUE TITLE
Release v0.1.0

### ISSUE THREAD

**Issue by batpad** [developmentseed/osm-seed#69]
We should create a release for `v0.1.0`:

 - Complete documentation: #65 (including clarification that this is a work in progress).
 - Create a `release` branch from `develop`
 - Tag a `v0.1.0` release: i.e. change the `version` in `package.json` and create a git tag.
 - Make a PR from the `release` branch to `master`
 - Merge PR to master
 - Merge master to develop

@olafveerman @Rub21 @geohacker - please let me know if there's anything else you'd consider pre-requisites for making a release, accompanied by making this repository open source.

**Comment by Rub21** [comment]
closing this ticket all the steps here was done!!
