### ISSUE TITLE
Cleanup cronjob pods 

### ISSUE THREAD

**Issue by Rub21** [developmentseed/osm-seed#93]
I notice the once they finished the job still are there, I had to remove manually,  those may overload the internal backlog system.
![image](https://user-images.githubusercontent.com/1152236/41988392-91311072-7a01-11e8-940b-3c5b9575277f.png)
cc. @batpad

**Comment by batpad** [comment]
Hmm I thought that was more just a log of the jobs completed and not like an existing resource. But I'm not fully sure. I'll check-up on whether they need to be deleted like that, that would seem odd.

**Comment by Rub21** [comment]
The cronjob pods were set to be active only during the execution!  it won't be active more than one.

done : here 👉  https://github.com/developmentseed/osm-seed/blob/develop/helm/osm-seed/templates/osmosis-job.yaml#L12-L13
