### ISSUE TITLE
Create other repositories for deployment

### ISSUE THREAD

**Issue by Rub21** [developmentseed/osm-seed#98]
So far the functionalities of docker + kubernetes are in the same repository, it seems to me that I should divide it into another repository like `osm-seed-kubernetes`, `osm-seed-aws`, and provide the necessary documentation in case people want to use any services of these services. and keep this repository only with docker updates or docker functionalities.
cc. @batpad @olafveerman

**Comment by batpad** [comment]
@Rub21 I think the current setup is fine. It includes a `docker-compose` configuration which is "stand-alone", and to deploy to cloud providers, it includes a Kubernetes configuration.

Within the Kubernetes configuration, we should do better at supporting different cloud providers, like GCP vs AWS, etc. This should be handled by making it configurable in the `Helm` Chart file. So ideally a user would be able to just set a variable in the Helm chart like `backend` to `GCP` or `AWS`, etc. and it would then configure things appropriately for GCP or AWS, but still require a Kubernetes cluster.

I don't think we want to support anything other than a single-node `docker-compose` setup and deploying to Kubernetes - like we don't want to support a setup using CloudFormation and ECS for example - and I think for that this single repository makes sense. However, it would be great to make a ticket for and start sketching out making the choice of cloud provider better configurable in the Helm chart. Does this make sense?

**Comment by Rub21** [comment]
thank you that makes sense!!
